require "http/client"
require "marten/cli"
require "set"
require "uri"

module MartenImportmap
  module CLI
    class Manage
      module Command
        class Importmap < Marten::CLI::Manage::Command::Base
          command_name :importmap
          help "Manage JavaScript import map entries."

          @subcommand : String?
          @library : String?
          @provider_name : String?

          private AUTO_GENERATED_MARKER      = "# AUTO-GENERATED by `marten importmap pin ...`"
          private CLI_FILE_PATH              = "src/cli.cr"
          private GENERATED_INITIALIZER_PATH = "config/initializers/importmap_pins.cr"
          private MANUAL_INITIALIZER_PATH    = "config/initializers/importmap.cr"
          private PROJECT_FILE_PATH          = "src/project.cr"
          private SETTINGS_FILE_PATH         = "config/settings/base.cr"
          private STARTER_JS_PATH            = "src/assets/application.js"
          private PIN_LINE_RE                = /^\s*pin\s+"((?:\\.|[^"\\])*)",\s+"((?:\\.|[^"\\])*)"\s*$/

          def setup
            on_argument(:subcommand, "Subcommand to execute (currently: init or pin)") do |value|
              @subcommand = value
            end

            on_argument(:library, "Name of the JavaScript library to pin") do |value|
              @library = value
            end

            on_option_with_arg(
              :from,
              arg: "provider",
              description: "Specify the package provider (for example: jsdelivr)"
            ) do |value|
              @provider_name = value
            end
          end

          def run
            if subcommand.nil?
              print_error_and_exit("Please provide an importmap subcommand (for example: init or pin)")
            end

            case subcommand
            when "init"
              run_init
            when "pin"
              run_pin
            else
              print_error_and_exit("Unsupported importmap subcommand '#{subcommand}'")
            end
          end

          protected def resolve_library(library : String, provider : MartenImportmap::Resolver::Provider)
            MartenImportmap::Resolver::Jspm.resolve_one(library, provider: provider)
          end

          protected def download_file(url : String, target_path : String)
            uri = URI.parse(url)

            tls = uri.scheme == "https"
            port = uri.port || (tls ? 443 : 80)
            host = uri.host || raise MartenImportmap::Resolver::Error.new("Invalid module URL '#{url}'")

            client = HTTP::Client.new(host, port, tls: tls)
            client.connect_timeout = 5.seconds
            client.read_timeout = 30.seconds
            client.write_timeout = 20.seconds

            path = uri.path
            path = "/" if path.empty?
            path += "?#{uri.query}" unless uri.query.nil?

            response = client.get(path)

            unless response.status.success?
              snippet = response.body[0, Math.min(500, response.body.bytesize)]
              raise MartenImportmap::Resolver::Error.new("HTTP #{response.status_code} while downloading #{url}: #{snippet}")
            end

            Dir.mkdir_p(File.dirname(target_path))
            File.write(target_path, response.body)
          rescue ex : IO::Error
            raise MartenImportmap::Resolver::Error.new("Failed to download #{url}: #{ex.message}")
          ensure
            client.try(&.close)
          end

          protected def project_root : Path
            Marten.root
          end

          protected def generated_initializer_path : String
            project_root.join(GENERATED_INITIALIZER_PATH).to_s
          end

          protected def manual_initializer_path : String
            project_root.join(MANUAL_INITIALIZER_PATH).to_s
          end

          protected def cli_file_path : String
            project_root.join(CLI_FILE_PATH).to_s
          end

          protected def project_file_path : String
            project_root.join(PROJECT_FILE_PATH).to_s
          end

          protected def settings_file_path : String
            project_root.join(SETTINGS_FILE_PATH).to_s
          end

          protected def starter_js_path : String
            project_root.join(STARTER_JS_PATH).to_s
          end

          private def run_init
            print(style("Initializing importmap support:", fore: :light_blue, mode: :bold), ending: "\n")
            ensure_project_requirement
            ensure_cli_requirement
            ensure_installed_app
            ensure_manual_initializer
            ensure_generated_initializer
            ensure_starter_js_entrypoint
          end

          private def run_pin
            library_name = library
            if library_name.nil?
              print_error_and_exit("Please provide a JavaScript library to pin")
              return
            end

            existing_entries = load_existing_entries
            provider = resolved_provider
            response = resolve_library(library_name, provider)
            imports = response.imports

            if imports.empty?
              print_error_and_exit("No import map entries were returned for '#{library}'")
            end

            pin_entries = if keep_cdn_urls?
                            imports
                          else
                            vendorize_imports(imports, existing_entries)
                          end

            write_generated_initializer(existing_entries.merge(pin_entries))
            print(
              "Updated #{generated_initializer_path} with #{pin_entries.size} #{pin_entries.size == 1 ? "pin" : "pins"}"
            )
          rescue ex : MartenImportmap::Resolver::Error
            print_error_and_exit(ex.message || "Unable to pin '#{library}'")
          end

          private def ensure_project_requirement
            print(%(› Ensuring #{style(%(require "marten_importmap"), fore: :cyan, mode: :bold)} in src/project.cr...), ending: "")

            path = project_file_path
            unless File.exists?(path)
              step_error("#{path} does not exist")
            end

            content = File.read(path)
            if content.includes?(%(require "marten_importmap"))
              step_skipped
              return
            end

            modified_content = content.sub(/require\s+"marten"(?:\s|$)/) do |match|
              %(#{match}require "marten_importmap"\n)
            end

            if modified_content == content
              step_error(%(Could not locate `require "marten"` in #{path}))
            end

            File.write(path, modified_content)
            step_done
          end

          private def ensure_cli_requirement
            print(%(› Ensuring #{style(%(require "marten_importmap/cli"), fore: :cyan, mode: :bold)} in src/cli.cr...), ending: "")

            path = cli_file_path
            unless File.exists?(path)
              step_skipped
              return
            end

            content = File.read(path)
            if content.includes?(%(require "marten_importmap/cli"))
              step_skipped
              return
            end

            modified_content = content.sub(/require\s+"marten\/cli"(?:\s|$)/) do |match|
              %(#{match}require "marten_importmap/cli"\n)
            end

            if modified_content == content
              step_error(%(Could not locate `require "marten/cli"` in #{path}))
            end

            File.write(path, modified_content)
            step_done
          end

          private def ensure_installed_app
            print(
              %(› Ensuring #{style("MartenImportmap::App", fore: :cyan, mode: :bold)} is in config.installed_apps...),
              ending: ""
            )

            path = settings_file_path
            unless File.exists?(path)
              step_error("#{path} does not exist")
            end

            content = File.read(path)
            if content.includes?("MartenImportmap::App")
              step_skipped
              return
            end

            modified_content = add_installed_app_to_settings(content)
            if modified_content.nil?
              step_error("Could not locate config.installed_apps in #{path}")
            end

            File.write(path, modified_content.not_nil!)
            step_done
          end

          private def ensure_manual_initializer
            print(
              %(› Ensuring #{style("config/initializers/importmap.cr", fore: :cyan, mode: :bold)} exists...),
              ending: ""
            )

            path = manual_initializer_path
            if File.exists?(path)
              step_skipped
              return
            end

            Dir.mkdir_p(File.dirname(path))
            File.write(path, build_manual_initializer_content)
            step_done
          end

          private def ensure_generated_initializer
            print(
              %(› Ensuring #{style("config/initializers/importmap_pins.cr", fore: :cyan, mode: :bold)} exists...),
              ending: ""
            )

            path = generated_initializer_path
            if File.exists?(path)
              unless File.read(path).includes?(AUTO_GENERATED_MARKER)
                step_error("Cannot manage #{path} because it is not an auto-generated pins initializer")
              end

              step_skipped
              return
            end

            write_generated_initializer({} of String => String)
            step_done
          end

          private def ensure_starter_js_entrypoint
            print(
              %(› Ensuring #{style("src/assets/application.js", fore: :cyan, mode: :bold)} exists...),
              ending: ""
            )

            path = starter_js_path
            if File.exists?(path)
              step_skipped
              return
            end

            Dir.mkdir_p(File.dirname(path))
            File.write(path, build_starter_js_content)
            step_done
          end

          private def keep_cdn_urls? : Bool
            importmap_settings.keep_cdn_urls? || false
          end

          private def resolved_provider : MartenImportmap::Resolver::Provider
            provider_label = provider_name
            return MartenImportmap::Resolver::Provider::JspmIo if provider_label.nil?

            provider = MartenImportmap::Resolver::Provider.from_cli(provider_label)
            return provider unless provider.nil?

            supported = MartenImportmap::Resolver::Provider.valid_values.join(", ")
            print_error_and_exit("Unsupported provider '#{provider_label}'. Supported providers: #{supported}")

            MartenImportmap::Resolver::Provider::JspmIo
          end

          private def vendorize_imports(
            imports : Hash(String, String),
            existing_entries : Hash(String, String),
          ) : Hash(String, String)
            vendor_dir = Path.new(importmap_settings.vendor_scripts_dir).expand.to_s
            used_paths = Set(String).new
            reserve_existing_vendor_paths(used_paths, existing_entries)

            output = {} of String => String

            imports.keys.sort!.each do |specifier|
              url = imports[specifier]

              target_path = existing_vendor_target(specifier, existing_entries) ||
                            next_vendor_target(vendor_dir, specifier, url, used_paths)

              download_file(url, target_path)

              used_paths << target_path
              output[specifier] = asset_relative_path(target_path)
            end

            output
          end

          private def reserve_existing_vendor_paths(used_paths : Set(String), entries : Hash(String, String))
            entries.each_value do |asset_path|
              next unless within_vendor_assets_dir?(asset_path)
              used_paths << Path.new("src/assets").join(asset_path).expand.to_s
            end
          end

          private def existing_vendor_target(
            specifier : String,
            existing_entries : Hash(String, String),
          ) : String?
            asset_path = existing_entries[specifier]?
            return unless asset_path && within_vendor_assets_dir?(asset_path)

            Path.new("src/assets").join(asset_path).expand.to_s
          end

          private def within_vendor_assets_dir?(asset_path : String) : Bool
            root = vendor_assets_root
            root_prefix = root.ends_with?("/") ? root : "#{root}/"

            asset_path == root || asset_path.starts_with?(root_prefix)
          end

          private def vendor_assets_root : String
            asset_relative_path(Path.new(importmap_settings.vendor_scripts_dir).expand.to_s)
          end

          private def next_vendor_target(
            vendor_dir : String,
            specifier : String,
            url : String,
            used_paths : Set(String),
          ) : String
            relative = normalized_vendor_relative_path(specifier, url)
            path = Path.new(vendor_dir).join(relative).normalize.to_s

            return path unless used_paths.includes?(path) || File.exists?(path)

            ext = File.extname(path)
            stem = path.sub(/#{Regex.escape(ext)}\z/, "")
            idx = 2

            loop do
              candidate = "#{stem}-#{idx}#{ext}"
              return candidate unless used_paths.includes?(candidate) || File.exists?(candidate)
              idx += 1
            end
          end

          private def normalized_vendor_relative_path(specifier : String, url : String) : String
            path = specifier.strip
            path = path.sub(/\A@/, "")
            path = path.gsub(/[^a-zA-Z0-9\-\._\/]/, "_")
            path = path.gsub(/\/+/, "/")

            segments = path
              .split("/")
              .reject(&.empty?)

            if segments.any? { |segment| segment == "." || segment == ".." }
              raise MartenImportmap::Resolver::Error.new("Invalid import specifier '#{specifier}' returned by resolver")
            end

            path = segments.join("/")
            path = "module" if path.empty?

            unless path.ends_with?(".js") || path.ends_with?(".mjs") || path.ends_with?(".cjs")
              path += inferred_extension(url)
            end

            path
          end

          private def inferred_extension(url : String) : String
            uri = URI.parse(url)
            ext = File.extname(uri.path).downcase

            case ext
            when ".js", ".mjs", ".cjs"
              ext
            else
              ".js"
            end
          rescue URI::Error
            ".js"
          end

          private def asset_relative_path(target_path : String) : String
            assets_root = Path.new("src/assets").expand.to_s
            root_prefix = assets_root.ends_with?("/") ? assets_root : "#{assets_root}/"
            expanded_target = Path.new(target_path).expand.to_s

            unless expanded_target.starts_with?(root_prefix)
              raise MartenImportmap::Resolver::Error.new(
                "Configured vendor_scripts_dir must be inside src/assets (current value: #{importmap_settings.vendor_scripts_dir})"
              )
            end

            expanded_target[root_prefix.size..-1]
          end

          private def importmap_settings : MartenImportmap::Configuration
            Marten.settings.importmap.as(MartenImportmap::Configuration)
          end

          private def load_existing_entries : Hash(String, String)
            path = generated_initializer_path
            unless File.exists?(path)
              raise MartenImportmap::Resolver::Error.new(
                "Importmap has not been initialized yet. Please run `marten importmap init` first."
              )
            end

            content = File.read(path)
            unless content.includes?(AUTO_GENERATED_MARKER)
              raise MartenImportmap::Resolver::Error.new(
                "Cannot update #{path} because it is not an auto-generated pins initializer"
              )
            end

            entries = {} of String => String

            content.each_line do |line|
              next unless match = PIN_LINE_RE.match(line)
              entries[unescape(match[1])] = unescape(match[2])
            end

            entries
          end

          private def write_generated_initializer(entries : Hash(String, String))
            path = generated_initializer_path
            Dir.mkdir_p(File.dirname(path))
            File.write(path, build_generated_initializer_content(entries))
          end

          private def build_manual_initializer_content : String
            String.build do |io|
              io.puts "Marten.configure do |config|"
              io.puts "  config.importmap.draw do"
              io.puts %(    pin "application", "application.js")
              io.puts "  end"
              io.puts "end"
            end
          end

          private def build_generated_initializer_content(entries : Hash(String, String)) : String
            String.build do |io|
              io.puts AUTO_GENERATED_MARKER
              io.puts "# DO NOT EDIT."
              io.puts
              io.puts "Marten.configure do |config|"
              io.puts "  config.importmap.draw do"

              entries.keys.sort!.each do |specifier|
                path = entries[specifier]
                io.puts %(    pin "#{escaped(specifier)}", "#{escaped(path)}")
              end

              io.puts "  end"
              io.puts "end"
            end
          end

          private def build_starter_js_content : String
            %(// Importmap entrypoint.\n)
          end

          private def add_installed_app_to_settings(content : String) : String?
            if match = content.match(/^(\h*)config\.installed_apps\s*=\s*\[\]\s*of\s+.+$/m)
              indent = match[1]
              replacement = [
                "#{indent}config.installed_apps = [",
                "#{indent}  MartenImportmap::App,",
                "#{indent}]",
              ].join("\n")

              return content.sub(match[0], replacement)
            end

            if match = content.match(/^(\h*)config\.installed_apps\s*=\s*\[([\s\S]*?)\]/m)
              indent = match[1]
              installed_app_names = match[2]
                .split(",")
                .map(&.strip)
                .reject(&.empty?)

              installed_app_names << "MartenImportmap::App"

              replacement = [
                "#{indent}config.installed_apps = [",
                installed_app_names.map { |item| "#{indent}  #{item}" }.join(",\n"),
                "#{indent}]",
              ].join("\n")

              return content.sub(match[0], replacement)
            end

            nil
          end

          private def step_done
            print(style(" DONE", fore: :light_green, mode: :bold))
          end

          private def step_skipped
            print(style(" SKIPPED", fore: :yellow, mode: :bold))
          end

          private def step_error(message : String) : NoReturn
            print(style(" ERROR", fore: :red, mode: :bold))
            print_error_and_exit(message)
          end

          private def escaped(value : String) : String
            value.gsub("\\", "\\\\").gsub("\"", "\\\"")
          end

          private def unescape(value : String) : String
            String.build do |io|
              escaping = false

              value.each_char do |char|
                if escaping
                  io << char
                  escaping = false
                elsif char == '\\'
                  escaping = true
                else
                  io << char
                end
              end

              io << '\\' if escaping
            end
          end

          private getter subcommand
          private getter library
          private getter provider_name
        end
      end
    end
  end
end
